
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Custom package installations 

;; Add files to load path 
(add-to-list 'load-path "~/.emacs.d/tabbar/")
(add-to-list 'load-path "~/.emacs.d/go-mode.el/")
(add-to-list 'load-path "~/.emacs.d/sbt-mode/")
(add-to-list 'load-path "~/.emacs.d/glsl-mode/")
(add-to-list 'load-path "~/.emacs.d/jade-mode/")
(add-to-list 'load-path "~/.emacs.d/emacs-neotree/")
(add-to-list 'load-path "~/.emacs.d/coffee-mode/")
(add-to-list 'load-path "~/.emacs.d/emacs-tss/")
(add-to-list 'load-path "~/.emacs.d/purescript-mode") 
(add-to-list 'load-path "~/.emacs.d/evil/") 
(add-to-list 'load-path "~/.emacs.d/emacs-elixir/") 
(add-to-list 'load-path "~/.emacs.d/undo-tree/")

;; Require packages 
(require 'go-mode-autoloads)
(require 'sbt-mode)
(require 'glsl-mode)
(require 'sws-mode)
(require 'jade-mode)
(require 'neotree)
(require 'coffee-mode)
(require 'typescript)
(require 'purescript-mode)
;(require 'purescript-mode-autoloads) 
(require 'evil)
(require 'elixir-mode) 
(require 'undo-tree)


;; Add Purescript information.
;; Note: purescript mode was giving me some kind of error-
;; not-error whenever it would try to use its indentation
;; mode setting. The add-hook line below specifies a default
;; indentation mode for purescript since I guess one isnt't
;; specified on initialization. 
(add-to-list 'Info-default-directory-list "~/.emacs.d/purescript-mode/")
(add-to-list 'safe-local-variable-values 'purescript-mode-hook)
(add-hook 'purescript-mode-hook 'turn-on-purescript-indentation) 


;; Enable evil mode
;(setq evil-toggle-key "<f4>") 
;(evil-mode 1) 


;; Add Auto modes 

;; Set filetypes to match with glsl editor 
(add-to-list 'auto-mode-alist '("\\.glsl\\'" . glsl-mode))
(add-to-list 'auto-mode-alist '("\\.vert\\'" . glsl-mode))
(add-to-list 'auto-mode-alist '("\\.frag\\'" . glsl-mode))
(add-to-list 'auto-mode-alist '("\\.shader\\'" . glsl-mode))
(add-to-list 'auto-mode-alist '("\\.geom\\'" . glsl-mode))

;; Auto mode for jade and stuff 
(add-to-list 'auto-mode-alist '("\\.styl\\'" . sws-mode))

;; Add Typescript to Auto modes 
(add-to-list 'auto-mode-alist '("\\.ts\\'" . typescript-mode))


;; Customizations for some stuff (auto-generated by emacs) 
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(coffee-tab-width 2)
 '(custom-safe-themes
   (quote
    ("72a81c54c97b9e5efcc3ea214382615649ebb539cb4f2fe3a46cd12af72c7607" "58c6711a3b568437bab07a30385d34aacf64156cc5137ea20e799984f4227265" default)))
 '(package-selected-packages
   (quote
    (load-theme-buffer-local magit tagedit paredit ido-ubiquitous clojure-mode-extra-font-locking eww-lnum tabbar rust-mode rainbow-delimiters projectile project-explorer js2-mode haskell-mode ensime cider better-defaults))))



